// <auto-generated />
namespace banksearchapp_Ivan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _777 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_777));
        
        string IMigrationMetadata.Id
        {
            get { return "201510152028466_777"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
